### ISSUE TITLE
Add Login with GitHub option

### ISSUE THREAD

**Issue by behdaad** [Text-Mining/Persian-NER#1]
As almost all of the people contributing to this project have a GitHub account, adding an option to login with GitHub will be much appreciated.

**Comment by Hameds** [comment]
Login with Google is planned but after all, we are developers. so we will add Github Login too :)

**Comment by behdaad** [comment]
Great to hear, keep up the good work.

**Comment by Hameds** [comment]
Google and GitHub login are here :)

![capture](https://user-images.githubusercontent.com/1385656/49342188-25bfe000-f66d-11e8-8c1c-19735161bc4f.PNG)
