### ISSUE TITLE
ایجاد نرم‌افزار موبایل برای تگ‌زنی

### ISSUE THREAD

**Issue by Hameds** [Text-Mining/Persian-NER#10]
<div dir="rtl">
برای راحت شدن تگ‌زنی برای افراد، پیشنهاد می‌شود که اپ موبایل ایجاد شود. این issue به بحث درباره امکانات این نرم‌افزار اختصاص دارد
</div>

**Comment by bkhezry** [comment]
برنامه رو میشه به ساده‌ترین صورت ممکن انجام داد. ورود و ثبت‌نام، نمایش یک جمله با قابلیت کلیک بر روی هر کلمه به صورت مجزا و ثبت دیتا به ازای هر کدوم و امکانی برای نمایش جمله بعدی

**Comment by Hameds** [comment]
<div dir="rtl">
اجرای همین حالت ساده با فرض آماده بودن API چقدر زمان می‌بره؟ امکان انتشار اپن سورس پروژه وجود داره؟
</div>

**Comment by bkhezry** [comment]
اگه همه چیز آماده باشه دو روز. بله حتما سورس رو منتشر می‌کنم

**Comment by tar944** [comment]
سلام
آقا من هم مشتاقم یه آپ بزنم
هم برای اندروید هم برای آیفون میشه کد بزنم
هر کدوم رو هم که بخواین بین ۲ تا ۴ روز با امکانات 
گفته شده طول می‌کشه

**Comment by Hameds** [comment]
<div dir="rtl">
@bkhezry و @tar944  نظرتون اینه که جاوا/کاتلین کد زده بشه یا از فریمورک‌هایی مثل react native استفاده کنیم
</div>

**Comment by Hameds** [comment]
<div dir="rtl">

نسخه اولیه مستندات API‌ پنل که در نرم‌افزار موبایل می‌تونه استفاده بشه در آدرس زیر قرار داره: 

[https://github.com/Text-Mining/Persian-NER/wiki/Panel-API](https://github.com/Text-Mining/Persian-NER/wiki/Panel-API)

</div>

**Comment by Hameds** [comment]
اپ اندروید ایجاد شد: https://github.com/Text-Mining/android-app
