### ISSUE TITLE
Change the UI input font family 

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [Text-Mining/Persian-NER#18]
```css
 font-family: cursive;
```

### Before:
![befor](https://user-images.githubusercontent.com/22220356/49370736-5b66d680-f70a-11e8-917a-cde3bc73d1f6.png)

### After:
![after](https://user-images.githubusercontent.com/22220356/49370739-5efa5d80-f70a-11e8-895a-30414ac7689d.png)

**Comment by Hameds** [comment]
Thanks for your suggestion. but right now UI changes like this is not in current development priorities. We are focused on fixing backed bugs and updating our APIs so although this is a low effort enhancement we can't spend time on this for now.
