### ISSUE TITLE
Use Ajax for submitting labels instead of reloading the page

### ISSUE THREAD

**Issue by behdaad** [Text-Mining/Persian-NER#2]
After submitting a label, page is reloaded. Not only this hinders the process of labeling tokens, it is very inefficient regarding network and server load.

**Comment by Hameds** [comment]
Thanks for the suggestion 👍 . We are working on this and you can consider it done.

**Comment by Hameds** [comment]
The final solution in our next major update is slightly different from this image and includes ajax for sentences too, but we deployed initial support for Ajax
![tag](https://user-images.githubusercontent.com/1385656/49330446-fa24f300-f5a3-11e8-9d45-3fadaefc0646.gif)
