### ISSUE TITLE
هماهنگ‌نبودن تعداد برچسب‌های زده‌شده با تعداد برچسب‌ها در لیست مشارکت‌کنندگان

### ISSUE THREAD

**Issue by GlassesPi** [Text-Mining/Persian-NER#37]
من از دیروز عصر متوجه شدم که یک اختلاف ثابت ۹ تایی بین تعداد برچسب‌های زده‌شده با تعداد برچسب‌ها در لیست مشارکت‌کنندگان دارم
![screenshot_20181211-185036](https://user-images.githubusercontent.com/30589130/49810396-66f37680-fd76-11e8-8095-3b99f331d037.png)

**Comment by Hameds** [comment]
newest release fixed this bug
