### ISSUE TITLE
رابط ساده‌تر جهت بیشتر شدن تمرکز کاربران

### ISSUE THREAD

**Issue by JKhakpour** [Text-Mining/Persian-NER#41]
این یک نظر شخصی هست بنابر مشاهداتم از دیگر نرم افزارهای برچسب‌زنی. به نظر من اگر صفحه تگ‌زنی رو ساده تر کنید روی دقت کاربر و کمتر خسته شدنش تاثیر زیادی داره. بهتره که منو و گزینه هاش، توضیحات پایین و سمت چپ همه تا جای ممکن حذف بشه یا قابلیت جمع شدن داشته باشن و جمله دقیقا وسط صفحه قرار بگیره.
اینطوری کار کردن با این ابزار هم میتونه راحت‌تر باشه

**Comment by Hameds** [comment]
<div dir="rtl">
پیشنهادتون بسیار خوبه و نظرتون کاملاً درسته. بخش راهنما و توضیحات مخزن اپن سورس رو به شکلی حذف می‌کنیم یا قابلیت جمع شدن رو بهشون اضافه می‌کنیم
</div>

**Comment by Hameds** [comment]
done
![capture](https://user-images.githubusercontent.com/1385656/50573654-7c941300-0ded-11e9-83ce-4913f837be8b.PNG)
