### ISSUE TITLE
امکان انتخاب به صورت یک range

### ISSUE THREAD

**Issue by JKhakpour** [Text-Mining/Persian-NER#42]
این ویژگی میتونه مزایا و معایب خودش رو داشته باشه ولی اگر بتونید به کاربر اجازه بدید که یک range رو یک جا انتخاب کنه و همه رو با هم تگ بزنه میتونه ویژگی جالبی برای رابط فعلی‌تون باشه

**Comment by Hameds** [comment]
<div dir="rtl">
با توجه به اینکه شروع entity رو مشخص می‌کنیم (مثلاً شروع سازمان یا شروع شخص) ایده‌ای برای پیاده سازی بهتر این امکان دارید؟ @JKhakpour 
</div>

**Comment by JKhakpour** [comment]
دقیقا متوجه سوالتون نشدم. ولی منظور من این بود که کاربر بتونه چند کلمه رو با ماوس انتخاب کنه و گزینه هایی رو برای انتخاب یکجای کلمات به عنوان یک ترکیب اسمی داشته باشه

منظورم ایطور چیزیه:
![screenshot from 2018-12-21 13-25-17](https://user-images.githubusercontent.com/1708467/50336662-eaa22580-0523-11e9-8b95-de0ce1adae00.png)

البته پیاده کردنش ممکنه نیاز به تغییر جدی داشته باشه تو رابط کاربری‌تون و خیلی قابل انجام نباشه. ولی به نظرم بحث کردن در موردش میتونه مفید باشه

**Comment by Hameds** [comment]
<div dir="rtl">
مساله‌ای که اشاره کردیم اینه که با توجه به اینکه ما شروع entity رو هم در نظر می‌گیریم، کاربر برای همون عبارت «سازمان قطار شهری تهران و حومه» باید اول کلمه «سازمان» رو به عنوان تگ «شروع سازمان» انتخاب کنه و بعد range «قطار شهری تهران و حومه» رو به عنوان تگ «سازمان» انتخاب کنه. 
</div>

**Comment by Hameds** [comment]
duplicate #3
