### ISSUE TITLE
امکان استفاده از کیبورد در تگ زدن (تگ زدن بدون نیاز به ماوس)

### ISSUE THREAD

**Issue by JKhakpour** [Text-Mining/Persian-NER#43]
این امکان که یک نفر بتونه با کیبورد بین کلمه‌ها حرکت کنه و با میان‌برهای تعریف شده برای هر تگ، اون کمه رو تگ بزنه و دوباره با کیبورد این جمله رو تایید کرده و بره به جمله بعدی میتونه سرعت کاربرهای جدی‌تون رو چند برابر کنه. البته اگر این کار  رو روی کامپیوترشون انجام  بدن.

**Comment by Hameds** [comment]
<div dir="rtl">
به نظرم این امکان رو به صورت اختیاری به کاربر بدیم تا اگر خواست به این شکل فعال کنه. نظر شما چیه @JKhakpour 
</div>

**Comment by JKhakpour** [comment]
تا جایی که من تو صفحه تگ‌زنی وبسایت دیدم، در حال حاضر همه کارها با ماوس انجام میشه. پس اضافه کردن کلیدهای میان‌بر تداخلی با کارکرد فعلی نداره و هر دو میتونن همزمان تو صفحه فعال باشن

**Comment by Hameds** [comment]
<div dir="rtl">
درست می‌فرمایید. امکان استفاده از این شیوه در دسکتاپ بدون اینکه اختلالی ایجاد کنه هست. در برنامه اجرایی قرار گرفته است. ممنون به خاطر پیشنهاد خوبتون
</div>
