### ISSUE TITLE
اصلاحات برچسب‌زنی پیکره پالایش نظرات

### ISSUE THREAD

**Issue by ehsanasgarian** [Text-Mining/Persian-NER#45]
۱- ajax کردن بخش برچسب‌زنی
۲- جایگزین کردن \r\n در متن پیام اینستاگرام
۳- افزودن شماره تعداد تگ زده شده به صفحه نخست

**Comment by Hameds** [comment]
<div dir="rtl">
بهتر است در هر issue یک درخواست مطرح شود تا پیگیری اجرا، بهتر باشد. از بین ۳ مورد مطرح شده فعلاً مورد ۳ به صفحه نخست اضافه می‌شود. مورد ۲ در حال کار است و مورد ۱ بعد از عرضه نسخه 2.0.0  کار خواهد شد
</div>

**Comment by Hameds** [comment]
<div dir="rtl">
مورد ۲ هم انجام شد
</div>
