### ISSUE TITLE
Custom Error page for 404 status

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [Text-Mining/Persian-NER#6]
This issue isn't force but you can consider that.
![2018-12-01_12-03-26](https://user-images.githubusercontent.com/22220356/49326039-59addf00-f561-11e8-913c-dcc936dd4e83.png)

**Comment by Hameds** [comment]
sure, it's a good idea

**Comment by Hameds** [comment]
now we have custom `404` and `500` error pages
![capture](https://user-images.githubusercontent.com/1385656/49336307-aef6f880-f614-11e8-9ac1-4da01cbd5d88.PNG)
