### ISSUE TITLE
انتشار جمله‌های برچسب زده شده توسط مشارکت کننده‌ها در این پروژه به صورت جداگانه

### ISSUE THREAD

**Issue by shayan72** [Text-Mining/Persian-NER#60]
در حال حاضر واضح نیست در دیتاست منتشر شده کدام جمله‌ها توسط مشارکت کننده‌ها در این پروژه برچسب‌گذاری شده‌اند و کدام‌ها از ابتدا بوده‌اند. 

پشنهاد می‌شود به صورت هفتگی یا روزانه تنها جمله‌های بررسی شده و برچسب زده شده توسط مشارکت کننده‌ها در این پروژه منتشر شود تا:

1. حجم خروجی در هر تکرار کاهش و سرعت خروجی گرفتن افزایش یابد
2. شفاف و واضح باشد که چه جمله‌هایی توسط مشارکت‌کننده‌ها بررسی شده و احتمال درستی آن‌ها بیشتر است
3. قابل تطابق با مقدار گزارش شده برای تعداد کل برچسب‌های زده شده توسط مشارکت‌کننده‌ها باشد. هر چند با توجه به این‌که یک جمله شاید توسط چندین کاربر برچسب‌گذاری شود، با این رویکرد ساده تطابق دقیق ممکن نیست، اما اتخاذ یک فرمت بهتر برای انتشار دقیق‌تر داده‌های جمع آوری شده می‌تواند در این پروژه و پروژه‌های مشابه آینده بسیار مهم و اعتمادساز باشد. برای مثال می‌توان لیست تمام برچسب‌های زده شده توسط هر کاربر را انتشار داد یا اینکه در دیتاست مشخص کرد که هر برچسب توسط چند کاربر تایید شده است.
4. اگر تمام یک میلیون جمله با موفقیت برچسب‌گذاری نشوند انتشار این تفکیک بسیار حائز اهمیت است

**Comment by vahidm** [comment]
من هم با این پیشنهاد موافقم. استفادهٔ علمی یا صنعتی از این پیکره در صورتی قابل اتکاست که تخمینی از دقت برچسب‌گذاری داشته باشیم. به نظر می‌رسد در حال حاضر نمی‌توان برای ساختن مدل از این پیکره استفاده کرد.
من داوطلب بهبود این روند هستم. البته اول باید در مورد #9 و احتمالاً بخش‌های مشابه تصمیمی گرفته شود.

**Comment by Hameds** [comment]
@shayan72 @vahidm در این خصوص در حال بررسی هستیم تا بدون ارائه مشخصات کاربران، داده‌ها منتشر شود. در واقع به روشی داده‌ها، ناشناس شوند و سپس منتشر شوند. تاکید بر این است که بعد از انتشار هم نتوان به هویت برچسب زننده رسید. به عنوان مثال در صفحه نخست پنل تحت وب، اطلاعات افراد مشارکت کننده برتر نمایش داده می‌شود. با شمارش تعداد تگ‌های یک کاربر می‌توان به هویت وی رسید. پیشنهادی دارید؟

**Comment by vahidm** [comment]
آیا نیازی داریم که مشخص شود هر برچسب‌گذاری توسط کدام کاربر انجام شده؟
به نظر من فقط مهم است بدانیم کدام جملات توسط کاربر بازنگری شده. برای این منظور هم انتشار جملات بازنگری شده در قالب یک پیکرهٔ جدا کافیست.
مشخص شدن کاربر (چه اطلاعات اصلی و چه به صورت ناشناس مثلاً با شناسهٔ تصادفی) در صورتی ارزشمند است که اطلاعاتی در مورد دقت کاربر داشته باشیم. برای مثال اگر بدانیم کاربر زمینهٔ زبانشناسی دارد یا خیر می‌تواند در استفاده از پیکره موثر باشد که فکر نمی‌کنم این ایده امکان بالایی داشته باشد.

**Comment by Hameds** [comment]
@vahidm ما الان یک فرمت میانی داریم که قبل از تبدیل به فایل اصلی در مخزن، از آن استفاده می‌کنیم. چنین شکلی دارد:

```
###2

بنیان‌گذاران	O
آن	O
،	O
جیمی	B-PER
ولز	I-PER
و	O
لری	B-PER
سنگر	I-PER
هستند	O
.	O

```

عدد بالای آن شماره جمله در کل دیتاست است. آیا انتشار همین فرمت میانی کمک می‌کند؟ فایل این فرمت میانی برای آخرین آپدیت مخزن، حدود ۶ مگابایت است. در این فرمت همچنین کاربران حذف شدند و عملاً آخرین برچسب‌زنی تایید شده را داریم

**Comment by Hameds** [comment]
<div dir="rtl">

در نهایت تصمیم بر آن شد تا به جای اینکه در خود مخزن، فایل جمله‌های برچسب‌زده شده اضافه شود، هر زمان آپدیتی بر روی دیتاست ایجاد می‌شود، نسخه جدیدی رلیز شده و فایل تغییرات تا آن نسخه، پیوست رلیز شود.


نخستین فایل تغییرات را از رلیز `1.2.0` می‌توانید دریافت کنید 
[https://github.com/Text-Mining/Persian-NER/releases/tag/v1.2.0](https://github.com/Text-Mining/Persian-NER/releases/tag/v1.2.0)


</div>
