### ISSUE TITLE
Check Github app permissions

### ISSUE THREAD

**Issue by Hameds** [Text-Mining/Persian-NER#61]
based on a question from this tweet : [https://twitter.com/geminorumir/status/1113599762375299073](https://twitter.com/geminorumir/status/1113599762375299073)
![Capture](https://user-images.githubusercontent.com/1385656/55665013-3071c800-584d-11e9-9f32-0ad8145adacf.PNG)

**Comment by Hameds** [comment]
It's resolved 
![Capture](https://user-images.githubusercontent.com/1385656/56107735-2fcbe680-5f5d-11e9-95a5-685e577d94d5.PNG)

**Comment by geminorum** [comment]
👍
