### ISSUE TITLE
سوال در مورد realease

### ISSUE THREAD

**Issue by reza1615** [Text-Mining/Persian-NER#62]
سلام 
در [اینجا](https://github.com/Text-Mining/Persian-NER/releases) چه فرقی بین متن‌های منبع و ریلیز هست؟
آیا متن منبع غیرقابل استناد و استفاده است؟ و توسط یک کد دیگر به صورت خودکار برچسب زده‌شده‌اند؟ آیا مواردی که در ریلیز هست ۱۰۰ درصد درست هستند؟

**Comment by Hameds** [comment]
<div dir="rtl">

سلام. رلیز، تفاوتی با فایل‌های منبع ندارد. در حقیقت، از مدتی پیش، بعد از هر آپدیت، نسخه جاری را رلیز کردیم. بر این اساس تفاوتی از نظر استفاده بین دانلود مستقیم فایل‌های مخزن یا دانلود از بخش رلیز نیست. تنها تفاوت بین رلیز و فایل‌های مخزن، این است که در هر رلیز، فایل جداگانه‌ای (که به مخزن کامیت نمی‌شود) و لیست جملات برچسب‌زده شده توسط کاربران است نیز همراه رلیز، عرضه می‌شود. این هم به خاطر پیشنهاد مطرح شده در #60 بوده است

</div>
