### ISSUE TITLE
connention error

### ISSUE THREAD

**Issue by zohreh3906** [Text-Mining/Persian-NER#65]
سلام.
Api ها ی موجود در سایت با چه ورژن از پایتون و requests کار میکنه؟
همس خطای connection error  می دهد

**Comment by Hameds** [comment]
<div dir="rtl">

با سلام و وقت بخیر
با توجه به تکراری بودن با #64 بسته می شود. پاسخ شما در ایمیل یا در #64 داده خواهد شد

</div>
