### ISSUE TITLE
سوال؟

### ISSUE THREAD

**Issue by zohreh3906** [Text-Mining/Persian-NER#66]
با سلام و احترام.
در کد زیر item2 در بخش POS و NER به چه معناست؟  
کاربردش چیه؟
![image](https://user-images.githubusercontent.com/37498680/63691370-43009400-c824-11e9-88f4-c96c8d9ae088.png)

**Comment by Hameds** [comment]
<div dir="rtl">

آیتم۲ مشخص می‌کنه که برچسب زده شده روی این توکن (در توکن بعدی) ادامه دارد یا خیر
مثلا «سازمان آب و فاضلاب»، سه کلمه «آب و فاضلاب» یک برچسب از نوع I-NER دارند و برچسب کلمه «آب» در کلمات بعدی ادامه دارد

</div>

**Comment by zohreh3906** [comment]
با سلام و عرض ادب
با عرض پوزش بنده فکر میکنم خروجی کارitem2 با تعریفی که شما ارائه دادید یکی نیست.
 اگر شما به مثال issue 66   نگاهی بیندازید منظورم رو متوجه میشود.
در این مثال آیتم برای کلمه "اسلامی" برابر ترو هست ولی این کلمه در کلمه بعدی تاثیری ندارد..
برای کلمه "عباسی" هم همینطور هست. 


حالا اگر از همه ی اینها بگذریم. آیا در ابزار شما این امکان وجود دارد که عبارت با برچسب موجودیت نامدارش رو بدهد؟ یعنی مثلا به جای اینکه توکن توکن به همراه برچسب بدهد عبارات مثل "سازمان کنفرانس ملی" یا " "جلال آل احمد " و یا همین "سازمان و آب و فاضلاب " را بدهد. 
ممنون میشوم کد آن را در اختیارم قرار دهید.
با تشکر

**Comment by zohreh3906** [comment]
با سلام و عرض ادب
با عرض پوزش بنده فکر میکنم خروجی کارitem2 با تعریفی که شما ارائه دادید یکی نیست.
اگر شما به مثال issue 66 نگاهی بیندازید منظورم رو متوجه میشود.
در این مثال آیتم برای کلمه "اسلامی" برابر ترو هست ولی این کلمه در کلمه بعدی تاثیری ندارد..
برای کلمه "عباسی" هم همینطور هست.

حالا اگر از همه ی اینها بگذریم. آیا در ابزار شما این امکان وجود دارد که عبارت با برچسب موجودیت نامدارش رو بدهد؟ یعنی مثلا به جای اینکه توکن توکن به همراه برچسب بدهد عبارات مثل "سازمان کنفرانس ملی" یا " "جلال آل احمد " و یا همین "سازمان و آب و فاضلاب " را بدهد.
ممنون میشوم کد آن را در اختیارم قرار دهید.
با تشکر
