### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zohreh3906** [Text-Mining/Persian-NER#67]
با سلام و احترام.
متاسفانه مشکل زیر پیش آمده. لطفا برطرف بفرمایید.
![63746331-d6d06f80-c8b9-11e9-88af-fd639d87172e](https://user-images.githubusercontent.com/1385656/63825108-a8609c00-c96e-11e9-8d1f-b9c7622e587b.png)

**Comment by Hameds** [comment]
closed because of [this comment](https://github.com/Text-Mining/Persian-NER/issues/68#issuecomment-527028884)
