### ISSUE TITLE
خطا در بین اجرا

### ISSUE THREAD

**Issue by zohreh3906** [Text-Mining/Persian-NER#68]
با سلام و احترام.

وقتی داده رو به تشخیص موجویدت نامدار می دهم و برنامه در حال اجرا هست به خطای زیر مواجه میشه و در حالیکه هنوز داده تمام نشده و همچنین هنوز تعداد کاراکتر به 3000 نرسیده که لازم به فراخوانی مجدد باشد. لطفا مشکل را برطرف کنید. 
البته با فراخوانی مجدد مشکل حل می شود ولی باید داده را از اول به  ای پی آی بدهم که نمیتوان اینکار رو انجام  بدهم چون اینکار بین لایه های  مدل دیپ لرنینگ داره انجام میشه
ممنون میشم مشکلش را برطرف کنید.

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Hameds** [comment]
<div dir="rtl">

@zohreh3906 آیا این ایراد با مورد مطرح شده در #67  متفاوت است؟

</div>

**Comment by zohreh3906** [comment]
در مورد #67 سایت شما کار نمیکرد و این خطا را میداد ولی در اینجا  سایت باز میشه و مشکلی ندارد ولی هر چند دقیقه یک بار این خطا می آید. و عملا پردازش های قبلی هم از بین میروند.

**Comment by ehsanasgarian** [comment]
اگر امکانش هست بخش کدی که ای.پی.آی متن کاوی را فراخوانی میکنید ضمیمه بفرمایید.

**Comment by ehsanasgarian** [comment]
لطفا با توجه به محدودیت منابع سرور و شرایط استفاده از ای.پی.آی رایگان، بین فراخوانی‌های متوالی کمی تاخیر بگذارید. مثلا بعد از هر فراخوانی از ۵۰۰ خیلی ثانیه تاخیر استفاده کنید
