### ISSUE TITLE
Authentication Cookie's Expire time is short

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [Text-Mining/Persian-NER#7]
The Authentication cookie's expire time is too short and when users change the URL or close tab they must login again and again.
Is it application policy?

![2018-12-01_12-11-06](https://user-images.githubusercontent.com/22220356/49326193-91b62180-f563-11e8-991d-b396361fc316.png)

**Comment by Hameds** [comment]
You are right. we are considering changing this policy after adding google login support

**Comment by Hameds** [comment]
Google login support added to the web app panel and this issue is resolved too
