### ISSUE TITLE
Named Entity Recognition not working

### ISSUE THREAD

**Issue by sakina-mosavi** [Text-Mining/Persian-NER#70]
### Description

url =  baseUrl + "NamedEntityRecognition/Detect"
payload = u'"احمد عباسی به تحصیلات خود در دانشگاه آزاد اسلامی در مشهد ادامه داد"'
result = json.loads(callApi(url, payload, tokenKey))
for phrase in result:
    print("("+phrase['word']+","+phrase['tags']['NER']['item1']+") ")
when I ran this code it doesn't have an output which is mentioned in the site.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and more step]

**Expected behavior:** 

[I expected to output a list but it output a string value]

**Actual behavior:**

[it output a string value]

### Versions

```
Browser: (ex: chrome 69)
OS: (ex: windows 10)
Platform: (web)
```

**Comment by ehsanasgarian** [comment]
Can you please describe error message or bad behaviour or (un)expected results, you are seeing?

**Comment by sakina-mosavi** [comment]
Thank you I fixed that sir.
I just wanted to know if there is any Library for Semantic Role Labeling
for Persian language.
sincerely:
sakina mosavi
