### ISSUE TITLE
The already taken (email or name)  validation message is English

### ISSUE THREAD

**Issue by devSoheilAlizadeh** [Text-Mining/Persian-NER#8]
When I want to register a new account with registered email address it shows the English validation message.

![2018-12-01_12-26-32](https://user-images.githubusercontent.com/22220356/49326244-95967380-f564-11e8-8d0c-9bec556129cf.png)

**Comment by Hameds** [comment]
seems that validation localization is not working properly. I will investigate this bug. Thanks for bug report
