### ISSUE TITLE
عدم رعایت دقت لازم در تحلیل احساسی

### ISSUE THREAD

**Issue by Clancyov** [Text-Mining/Persian-NER#82]
با عرض سلام و خسته نباشید.
قبل از هرچیز متشکرم که همچین سرویس مهمی رو توسعه دادید و در اختیار عموم به رایگان گذاشتید.
دقایقی قبل از سرویس تحلیل احساسی متن استفاده کردم و متاسفانه برای بعضی کلمات بسیار ساده دقت لازم را نداشت برای مثال باید عرض کنم که کلمه "خوب" را منفی تشخیص داد! حتی "خوب است" و یکسری ترکیبات دیگر را نیز اعمال کردم اما نتیجه همجنان منفی بود.

**Comment by ehsanasgarian** [comment]
ممنون از توجه شما
سرویس جدید تحلیل حس ما SentimentClassifier2 هست که لطفا از این سرویس استفاده کنید
چون سرویس جدید خروجی متفاوتی با سرویس قدیمی (SentimentClassifier) داشت و برای بهم نخوردن کد دوستانی که از سرویس قدیمی استفاده میکردن، سرویس جدید جایگزین سرویس قدیم نشد و با نام جدید منتشر شد

![image](https://github.com/Text-Mining/Persian-NER/assets/14190410/40384b2c-432b-4aa0-9da4-707789a2f86e)
